eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9091/eureka/
fetch-registry: true
##management:
##    security:
##        enabled: false
register-with-eureka: true
server:
    port: 8088
spring:
    application:
        name: TrackService
##    cloud:
##        config:
##            server:
##                git:
##                    uri: https://github.com/Nalinshankar/config-server-repo
##    data:
##        mongodb:
##            database: Muzix1
##            host: localhost
##            port: 27017


