#server.port=8888
#spring.application.name=config-server
#spring.cloud.config.server.git.uri=https://github.com/Nalinshankar/config-server-repo
#management.security.enabled=false
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8882/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true


server:
  port: 8066
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          force-pull: true
          uri: https://github.com/Nalinshankar/config-server-repo